Updates
NBISweden/sda-services-backup pull request #398
Opened 2022-12-16 07:07 UTC by jbygdell

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

1) update python to 3.10
2) add github actions to dependabot checks

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2022-12-16 13:26 UTC, norling commented
I think this breaks if an ingest message is followed by a cancel message, but the ingest message is then nack'ed and requeued. This will cause the cancel message to give an error when trying to update the database, but then the cancel message is still Ack'ed. Once the queue gets back to the requeued ingest message it's gonna be ingested right?

2022-12-16 13:34 UTC, norling requested changes

2022-12-16 13:34 UTC, norling commented on .github/dependabot.yml
> +      - aaperis
I think kostas has proved good enough to also be in the list by now ^^

2023-01-08 07:44 UTC, norling approved these changes

2023-01-09 08:28 UTC, dbampalikis approved these changes

2023-01-09 08:29 UTC, merged